/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * central_api
 * OpenAPI spec version: 1.0.0
 */
import type { UserRole } from './userRole';

export interface AuthedUser {
  /** Your defined role. */
  role: UserRole;
  /** The email the user used to register his account */
  email: string;
  /** The unique internal id. */
  id: number;
}
