/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * central_api
 * OpenAPI spec version: 1.0.0
 */

/**
 * The login request.
 */
export interface LoginRequest {
  /** The password used to login. */
  password: string;
  /** The email the user used to register his account */
  email: string;
}
