/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * central_api
 * OpenAPI spec version: 1.0.0
 */

export type LoginResponseAllOf = {
  /** The token used for auth. */
  token: string;
};
