/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * central_api
 * OpenAPI spec version: 1.0.0
 */
import type { AuthedUser } from './authedUser';
import type { LoginResponseAllOf } from './loginResponseAllOf';

/**
 * The authenticated user's details.
 */
export type LoginResponse = AuthedUser & LoginResponseAllOf;
