/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * central_api
 * OpenAPI spec version: 1.0.0
 */

export interface TodoResponse {
  id: number;
  description: string;
  userEmail: string;
}
