/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * central_api
 * OpenAPI spec version: 1.0.0
 */

/**
 * Model Todo
 */
export interface Todo {
  authorId: number;
  description: string;
  updatedAt: string;
  createdAt: string;
  id: number;
}
