/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * central_api
 * OpenAPI spec version: 1.0.0
 */

/**
 * Model User
 */
export interface User {
  passwordHash: string | null;
  role: string;
  email: string;
  updatedAt: string;
  createdAt: string;
  id: number;
}
